### ISSUE TITLE
delaying one minute to publish

### ISSUE THREAD

**Issue by divakarmuppidi** [ComfortablyCoding/strapi-plugin-publisher#87]
The entry was publishing one minute after to the time we set

**Comment by ComfortablyCoding** [comment]
That is expected behaviour, the Cron only runs every minute to check for published articles. Due to this they can be set to published up to a minute past the set datetime. The publish datetime value should be correct though.

If you wish to increase or change this frequency you can do so via the actions.syncFrequency outlined in the docs.
